version: '3.8'
services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql_server_mascotas
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_cuidadomascotas
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:

